### ISSUE TITLE
Страница на која не се блокирани рекламите

### ISSUE THREAD

**Issue by jakche** [DeepSpaceHarbor/Macedonian-adBlock-Filters#15]
[https://stanica.mk](https://stanica.mk/)

Исто така ете и[ една статија](https://stanica.mk/vesti/doma-vesti/prilepchanec-napadnat-od-majstorite-koi-gi-angazhiral-da-mu-rabotat-vo-negoviot-dom/) на која има премногу реклами, ако не се сите на почетнат страница.

**Comment by DeepSpaceHarbor** [comment]
👋  tnx for the bug report!

Додадов нови правила за станица, најголем дел од рекламите се скриени. За жал, на дел од постовите има реклами кои што неможам да ги фатам со ниту едно правило. HTML елементот од сликата со рекламата е ист со HTML елементот од сликата поврзана со постот. Има опција рачно да се блокира реклама по реклама според адресата на сликата, ама за недела-две ке се сменат рекламите и пак се враќаме на почетниот проблем.

**Comment by jakche** [comment]
Ти благодарам за објаснувањето, сепак подобро е искуството на страницата со сегашниот update.
