### ISSUE TITLE
Update the README

### ISSUE THREAD

**Issue by MasterKia** [DeepSpaceHarbor/Macedonian-adBlock-Filters#3]
https://github.com/gorhill/uBlock/commit/088e90ed42cdb09828b71a799425bb0ed0dab21c

Hi, your list has been added to uBlock Origin (I hope AdGuard will do the same soon).
It will be available to all users after ~13 days (I think).
After that, it will be available in the "Regions, languages" section for all users to enable and then there's no need to manually enable the list anymore.

**Comment by DeepSpaceHarbor** [comment]
The readme file has been updated. 

Thank you @MasterKia and @DandelionSprout for your help. :heart:

**Comment by DeepSpaceHarbor** [comment]
Thanks for letting me know @MasterKia, I'll update the filters list right away.
