### ISSUE TITLE
Import filters from AdGuard Base foreign section

### ISSUE THREAD

**Issue by MasterKia** [DeepSpaceHarbor/Macedonian-adBlock-Filters#4]
AdGuard Base has a section for Macedonian sites:

https://github.com/AdguardTeam/AdguardFilters/blob/master/BaseFilter/sections/foreign.txt#L5028-L5052

If all of those sites are covered in your list, then a pull request<sup>[1]</sup> could be sent to remove those filters from AdGuard Base.

[1]: Well actually we should have to wait until your list is officially added to AdGuard (https://github.com/AdguardTeam/FiltersRegistry/issues/354 and https://github.com/AdguardTeam/FiltersRegistry/pull/752).

**Comment by DeepSpaceHarbor** [comment]
:wave:  Thanks for the notice! 
I copied the filters from AdGuard and added a couple of them that were missing for the target websites. 
Everything should be ok now.
